#!/bin/sh

configoptions="\
--disable-all \
--disable-short-tags \
--disable-sigchild \
--with-layout=GNU \
--with-regex \
--with-openssl=shared \
--with-zlib=shared \
--enable-bcmath=shared \
--with-bz2=shared \
--enable-calendar=shared \
--with-gettext=shared \
--enable-mbstring=shared \
--enable-pcntl=shared \
--enable-soap=shared \
--enable-sockets=shared \
--with-pdo-sqlite \
--enable-sysvmsg=shared \
--enable-sysvsem=shared \
--enable-sysvshm=shared \
--with-xsl=shared \
--with-iconv=shared \
--enable-zip=shared \
--enable-posix=shared \
--enable-libxml=shared \
--enable-dom=shared \
--enable-xml=shared \
--enable-xmlreader=shared \
--enable-xmlwriter=shared \
--enable-tokenizer=shared \
--enable-pdo \
--enable-ctype=shared \
--enable-json=shared \
--enable-session=shared \
--enable-soap=shared \
--enable-filter \
--with-gmp=shared \
--with-readline \
--disable-mysqlnd-compression-support \
"
