#!/bin/sh

configoptions="\
--disable-all \
--disable-short-tags \
--disable-sigchild \
--with-layout=GNU \
--with-regex \
--with-openssl \
--with-zlib \
--enable-bcmath \
--with-bz2 \
--enable-calendar \
--with-gd \
--enable-gd-native-ttf \
--with-gettext \
--with-gmp \
--enable-mbstring \
--enable-pcntl \
--with-readline \
--enable-simplexml \
--enable-soap \
--enable-sockets \
--with-pdo-sqlite \
--enable-sysvmsg \
--enable-sysvsem \
--enable-sysvshm \
--with-xsl \
--with-iconv \
--enable-zip \
--enable-posix \
--enable-libxml \
--enable-dom \
--enable-xml \
--enable-xmlreader \
--enable-xmlwriter \
--enable-simplexml \
--enable-tokenizer \
--enable-pdo \
--enable-ctype \
--enable-json \
--enable-session \
"
